.travis.yml, app/controllers/users.js, app/models/tweets.js, app/models/user.js, app/views/tweets/index.jade, app/views/users/list.jade, config/config.js, config/passport.js, config/routes.js
Only github will be used for login, removing facebook and twitter.
=> try and fix login again

config/passport.js, package.json
Reported-by:
Signed-off-by: Vinit Kumar <vinit1414.08@bitmesra.ac.in>
=> cleanup code and fix crash on new users

app/controllers/tweets.js, app/controllers/users.js, app/models/analytics.js
This model will be use to log the ip of the users who visit
node twitter.
Reported-by:
Signed-off-by: Vinit Kumar <vinit1414.08@bitmesra.ac.in>
=> Add new model for analytics.

app/controllers/tweets.js, app/controllers/users.js, app/models/tweets.js, app/views/tweets/index.pug, app/views/tweets/tweets.pug, app/views/users/profile.pug
=> Styled the profile tweets similar to home page tweets

public/js/app.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/129)
=> fix the issue with broken follow

app/models/tweets.js, app/models/user.js, app/views/tweets/index.pug, app/views/tweets/show.pug, app/views/tweets/tweets.pug, app/views/users/list.pug, app/views/users/profile.pug, config/config.example.js, config/config.local.js, config/routes.js, package-lock.json, package.json
Fixes #125
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/131)
=> Remove unused Facebook and Twitter authentication code

app/views/includes/header.pug, app/views/tweets/index.pug
Fixes #123 
@vinitkumar This is ready for review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/142)
=> Tweets can now be composed from any page where a user is authenticated

app/views/users/profile.pug
Fixes #124 
@vinitkumar This is ready for review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/148)
=> Fixed the Github link on user profiles

public/css/style.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/147)
=> Fixed the issue with analytics table being oversized with long URLs

app/views/tweets/tweets.pug
I'm not too sure if I have to locally build but I haven't edited any code, only HTML, so shouldn't have broken anything
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/149)
=> Fixed inconsistency in buttons - Edit is capital and so should Delete be

config/express.js, package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/150)
=> add sentry config

app/controllers/analytics.js, app/controllers/tweets.js, app/views/tweets/index.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/153)
=> fixes #145, fix missing pagination

public/css/style.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/155)
=> Made error text readable

app/controllers/analytics.js, app/controllers/tweets.js, app/models/tweets.js, app/views/tweets/index.pug, package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/156)
=> add tweet pagination and fix tweet max length

app/controllers/analytics.js, app/controllers/tweets.js, app/models/tweets.js, app/views/500.pug, app/views/tweets/index.pug, app/views/tweets/tweets.pug, app/views/users/profile.pug, public/css/style.css
- add validation to the tweet and commit length
- add pagination to the tweet page
- fix crash in case the page lands where tweets where created from fb, twitter.
- same as above for profile page
- make the stack trace much more readable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/157)
=> fix some bugs in the app

app/controllers/tweets.js, app/models/user.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/161)
=> fixes #159, incorrect user tweets count

.eslintrc.js, app/controllers/users.js, app/views/includes/footer.pug, app/views/useful-links.pug, app/views/users/followers.pug, app/views/users/following.pug, public/css/style.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/165)
=> add some minor improvements to the follower and following page

app/controllers/tweets.js, app/views/components/tweets.pug, config/express.js
- Issue number:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/186)
=> Fix problem with unability to delete tweets

app/controllers/analytics.js, app/models/user.js, app/views/pages/analytics.pug
Put a text displaying total users on analytics page with minor improvement on text "Visits" and "Tweets"
#144 
- [ x ] New feature (non-breaking change which adds functionality)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/204)
=> Display total users on Analytics Page - Issue #144

app/controllers/chat.js, app/controllers/comments.js, app/controllers/follows.js, app/models/activity.js, app/models/notification.js, app/models/tweets.js, app/models/user.js, package-lock.json, package.json
Issue: #203
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/205)
=> Activity and Notification Stream

app/views/pages/login.pug, public/css/style.css
Change markup and add style to improve analytics section on login page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/206)
=> Improvement: Analytics section on login page,

CONTRIBUTING.md, package.json
This pull request adds backers and sponsors from your Open Collective https://opencollective.com/node-twitter ❤️
It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
We have also added a `postinstall` script to let people know after `npm|yarn install` that you are welcoming donations (optional). [[More info](https://github.com/OpenCollective/opencollective-cli)]
You can also add a "Donate" button to your website and automatically show your backers and sponsors there …
=> Activating Open Collective

app/controllers/activity.js, app/controllers/analytics.js, app/controllers/apiv1.js, app/controllers/chat.js, app/controllers/comments.js, app/controllers/follows.js, app/controllers/tweets.js, app/controllers/users.js, app/middlewares/logger.js, config/express.js, package-lock.json, package.json
- add new Eslint config
- Remove console.log usages in all controllers
- More code quality fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/211)
=> Style fixes

config/middlewares/logger.js, test/fixtures/users.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/214)
=> node-twitter-213 do not log duplicate analytics on the same day

app/views/components/profile-card.pug
Removed ahref from username from profile page
Fixes #196 
Added screen shot added in issue discussion
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/218)
=> Removed link to Github profile from profile page username

app/views/pages/login.pug, public/css/style.css
Added top margin to login button, to have some spacing between `Node Twitter` header and login button
#194 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/222)
=> added top margin to login button

LICENSE
Let's switch to a more liberal license to make it more contribution friendly.
_Issue number being fixed (Format: Fixes #xxx)_
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/229)
=> related #228, change license from gplv3 to Apache

lib/utils.js, public/js/app.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/232)
=> fix: clean some code

Dockerfile, Makefile, config/config.js, docker-compose.yml, package-lock.json, package.json, readme.md
_Issue number being fixed (Format: Fixes #xxx)_
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/237)
=> feat: setup docker, docker-compose based setup

app/views/layouts/footer.pug, readme.md
_Issue number being fixed (Format: Fixes #xxx)_
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/239)
=> fix: outdated license names

package-lock.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/240)
=> fix: remove outdated packages that were causing issues with licenses

app/controllers/analytics.js, app/controllers/apiv1.js, app/controllers/chat.js, app/controllers/users.js, app/models/tweets.js, app/models/user.js, config/express.js, config/middlewares/authorization.js, server.js
Fix some issues and other small bugs fixed. Upgrade `count` method to `countDocuments`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/260)
=> fix: update code as per the new warnings due to upgraded mongoose

readme.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/262)
=> Change port back to 3000 in readme

config/middlewares/logger.js
_Issue number being fixed (Format: Fixes #270)_
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/271)
=> Fix issue with analytics now working for new users

app/views/chat/chat.pug, app/views/components/comments.pug, app/views/components/tweet.pug, app/views/pages/activity.pug, app/views/pages/analytics.pug
Formatted the output of date and time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vinitkumar/node-twitter/274)
=> Replaced dateFormat() to moment().format()
